GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6270c793bb115bfb326be364

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Hoang",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/6270c793bb115bfb326be364

###

PATCH http://localhost:3000/subscribers/6270c793bb115bfb326be364
Content-Type: application/json

{
    "name": "Duong"
}